server:
  port: 6969

spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: productcrud
  jpa:
    hibernate:
      ddl-auto: update

profanityfilter:
  base-url: https://api.api-ninjas.com/v1/profanityfilter
  api-key: 7oj1WuhNxI77flVgDlT+fA==WASbgA5oEs0xa5Xv
